package com.koiy.playercompanion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class StrategySets {


    public List<List<String>> getMatrix256() {

        List<String> set1 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "O", "O", "O", "O"));
        List<String> set2 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "E", "E", "E", "E"));
        List<String> set3 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "O", "O", "O", "E"));
        List<String> set4 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "E", "E", "E", "O"));
        List<String> set5 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "O", "O", "E", "E"));
        List<String> set6 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "E", "E", "O", "O"));
        List<String> set7 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "O", "E", "O", "O"));
        List<String> set8 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "E", "O", "E", "E"));
        List<String> set9 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "O", "E", "E", "E"));
        List<String> set10 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "E", "O", "O", "O"));
        List<String> set11 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "O", "E", "E", "O"));
        List<String> set12 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "E", "O", "O", "E"));
        List<String> set13 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "O", "O", "E", "O"));
        List<String> set14 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "E", "E", "O", "E"));
        List<String> set15 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "O", "E", "O", "E"));
        List<String> set16 = new ArrayList<>(Arrays.asList("E", "E", "E", "E", "E", "O", "E", "O"));
        List<String> set17 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "O", "O", "O", "O"));
        List<String> set18 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "E", "E", "E", "E"));
        List<String> set19 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "O", "O", "O", "E"));
        List<String> set20 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "E", "E", "E", "O"));
        List<String> set21 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "O", "O", "E", "E"));
        List<String> set22 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "E", "E", "O", "O"));
        List<String> set23 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "O", "E", "O", "O"));
        List<String> set24 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "E", "O", "E", "E"));
        List<String> set25 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "O", "E", "E", "E"));
        List<String> set26 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "E", "O", "O", "O"));
        List<String> set27 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "O", "E", "E", "O"));
        List<String> set28 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "E", "O", "O", "E"));
        List<String> set29 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "O", "O", "E", "O"));
        List<String> set30 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "E", "E", "O", "E"));
        List<String> set31 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "O", "E", "O", "E"));
        List<String> set32 = new ArrayList<>(Arrays.asList("O", "O", "O", "O", "E", "O", "E", "O"));
        List<String> set33 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "O", "O", "O", "O"));
        List<String> set34 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "E", "E", "E", "E"));
        List<String> set35 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "O", "O", "O", "E"));
        List<String> set36 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "E", "E", "E", "O"));
        List<String> set37 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "O", "O", "E", "E"));
        List<String> set38 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "E", "E", "O", "O"));
        List<String> set39 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "O", "E", "O", "O"));
        List<String> set40 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "E", "O", "E", "E"));
        List<String> set41 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "O", "E", "E", "E"));
        List<String> set42 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "E", "O", "O", "O"));
        List<String> set43 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "O", "E", "E", "O"));
        List<String> set44 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "E", "O", "O", "E"));
        List<String> set45 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "O", "O", "E", "O"));
        List<String> set46 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "E", "E", "O", "E"));
        List<String> set47 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "O", "E", "O", "E"));
        List<String> set48 = new ArrayList<>(Arrays.asList("E", "O", "E", "O", "E", "O", "E", "O"));
        List<String> set49 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "O", "O", "O", "O"));
        List<String> set50 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "E", "E", "E", "E"));
        List<String> set51 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "O", "O", "O", "E"));
        List<String> set52 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "E", "E", "E", "O"));
        List<String> set53 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "O", "O", "E", "E"));
        List<String> set54 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "E", "E", "O", "O"));
        List<String> set55 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "O", "E", "O", "O"));
        List<String> set56 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "E", "O", "E", "E"));
        List<String> set57 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "O", "E", "E", "E"));
        List<String> set58 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "E", "O", "O", "O"));
        List<String> set59 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "O", "E", "E", "O"));
        List<String> set60 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "E", "O", "O", "E"));
        List<String> set61 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "O", "O", "E", "O"));
        List<String> set62 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "E", "E", "O", "E"));
        List<String> set63 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "O", "E", "O", "E"));
        List<String> set64 = new ArrayList<>(Arrays.asList("O", "E", "O", "E", "E", "O", "E", "O"));
        List<String> set65 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "O", "O", "O", "O"));
        List<String> set66 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "E", "E", "E", "E"));
        List<String> set67 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "O", "O", "O", "E"));
        List<String> set68 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "E", "E", "E", "O"));
        List<String> set69 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "O", "O", "E", "E"));
        List<String> set70 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "E", "E", "O", "O"));
        List<String> set71 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "O", "E", "O", "O"));
        List<String> set72 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "E", "O", "E", "E"));
        List<String> set73 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "O", "E", "E", "E"));
        List<String> set74 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "E", "O", "O", "O"));
        List<String> set75 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "O", "E", "E", "O"));
        List<String> set76 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "E", "O", "O", "E"));
        List<String> set77 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "O", "O", "E", "O"));
        List<String> set78 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "E", "E", "O", "E"));
        List<String> set79 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "O", "E", "O", "E"));
        List<String> set80 = new ArrayList<>(Arrays.asList("E", "E", "E", "O", "E", "O", "E", "O"));
        List<String> set81 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "O", "O", "O", "O"));
        List<String> set82 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "E", "E", "E", "E"));
        List<String> set83 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "O", "O", "O", "E"));
        List<String> set84 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "E", "E", "E", "O"));
        List<String> set85 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "O", "O", "E", "E"));
        List<String> set86 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "E", "E", "O", "O"));
        List<String> set87 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "O", "E", "O", "O"));
        List<String> set88 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "E", "O", "E", "E"));
        List<String> set89 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "O", "E", "E", "E"));
        List<String> set90 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "E", "O", "O", "O"));
        List<String> set91 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "O", "E", "E", "O"));
        List<String> set92 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "E", "O", "O", "E"));
        List<String> set93 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "O", "O", "E", "O"));
        List<String> set94 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "E", "E", "O", "E"));
        List<String> set95 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "O", "E", "O", "E"));
        List<String> set96 = new ArrayList<>(Arrays.asList("O", "O", "O", "E", "E", "O", "E", "O"));
        List<String> set97 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "O", "O", "O", "O"));
        List<String> set98 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "E", "E", "E", "E"));
        List<String> set99 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "O", "O", "O", "E"));
        List<String> set100 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "E", "E", "E", "O"));
        List<String> set101 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "O", "O", "E", "E"));
        List<String> set102 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "E", "E", "O", "O"));
        List<String> set103 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "O", "E", "O", "O"));
        List<String> set104 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "E", "O", "E", "E"));
        List<String> set105 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "O", "E", "E", "E"));
        List<String> set106 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "E", "O", "O", "O"));
        List<String> set107 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "O", "E", "E", "O"));
        List<String> set108 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "E", "O", "O", "E"));
        List<String> set109 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "O", "O", "E", "O"));
        List<String> set110 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "E", "E", "O", "E"));
        List<String> set111 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "O", "E", "O", "E"));
        List<String> set112 = new ArrayList<>(Arrays.asList("E", "E", "O", "E", "E", "O", "E", "O"));
        List<String> set113 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "O", "O", "O", "O"));
        List<String> set114 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "E", "E", "E", "E"));
        List<String> set115 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "O", "O", "O", "E"));
        List<String> set116 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "E", "E", "E", "O"));
        List<String> set117 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "O", "O", "E", "E"));
        List<String> set118 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "E", "E", "O", "O"));
        List<String> set119 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "O", "E", "O", "O"));
        List<String> set120 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "E", "O", "E", "E"));
        List<String> set121 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "O", "E", "E", "E"));
        List<String> set122 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "E", "O", "O", "O"));
        List<String> set123 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "O", "E", "E", "O"));
        List<String> set124 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "E", "O", "O", "E"));
        List<String> set125 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "O", "O", "E", "O"));
        List<String> set126 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "E", "E", "O", "E"));
        List<String> set127 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "O", "E", "O", "E"));
        List<String> set128 = new ArrayList<>(Arrays.asList("O", "O", "E", "O", "E", "O", "E", "O"));
        List<String> set129 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "O", "O", "O", "O"));
        List<String> set130 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "E", "E", "E", "E"));
        List<String> set131 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "O", "O", "O", "E"));
        List<String> set132 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "E", "E", "E", "O"));
        List<String> set133 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "O", "O", "E", "E"));
        List<String> set134 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "E", "E", "O", "O"));
        List<String> set135 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "O", "E", "O", "O"));
        List<String> set136 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "E", "O", "E", "E"));
        List<String> set137 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "O", "E", "E", "E"));
        List<String> set138 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "E", "O", "O", "O"));
        List<String> set139 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "O", "E", "E", "O"));
        List<String> set140 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "E", "O", "O", "E"));
        List<String> set141 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "O", "O", "E", "O"));
        List<String> set142 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "E", "E", "O", "E"));
        List<String> set143 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "O", "E", "O", "E"));
        List<String> set144 = new ArrayList<>(Arrays.asList("E", "O", "E", "E", "E", "O", "E", "O"));
        List<String> set145 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "O", "O", "O", "O"));
        List<String> set146 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "E", "E", "E", "E"));
        List<String> set147 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "O", "O", "O", "E"));
        List<String> set148 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "E", "E", "E", "O"));
        List<String> set149 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "O", "O", "E", "E"));
        List<String> set150 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "E", "E", "O", "O"));
        List<String> set151 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "O", "E", "O", "O"));
        List<String> set152 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "E", "O", "E", "E"));
        List<String> set153 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "O", "E", "E", "E"));
        List<String> set154 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "E", "O", "O", "O"));
        List<String> set155 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "O", "E", "E", "O"));
        List<String> set156 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "E", "O", "O", "E"));
        List<String> set157 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "O", "O", "E", "O"));
        List<String> set158 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "E", "E", "O", "E"));
        List<String> set159 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "O", "E", "O", "E"));
        List<String> set160 = new ArrayList<>(Arrays.asList("O", "E", "O", "O", "E", "O", "E", "O"));
        List<String> set161 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "O", "O", "O", "O"));
        List<String> set162 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "E", "E", "E", "E"));
        List<String> set163 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "O", "O", "O", "E"));
        List<String> set164 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "E", "E", "E", "O"));
        List<String> set165 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "O", "O", "E", "E"));
        List<String> set166 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "E", "E", "O", "O"));
        List<String> set167 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "O", "E", "O", "O"));
        List<String> set168 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "E", "O", "E", "E"));
        List<String> set169 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "O", "E", "E", "E"));
        List<String> set170 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "E", "O", "O", "O"));
        List<String> set171 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "O", "E", "E", "O"));
        List<String> set172 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "E", "O", "O", "E"));
        List<String> set173 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "O", "O", "E", "O"));
        List<String> set174 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "E", "E", "O", "E"));
        List<String> set175 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "O", "E", "O", "E"));
        List<String> set176 = new ArrayList<>(Arrays.asList("O", "E", "E", "E", "E", "O", "E", "O"));
        List<String> set177 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "O", "O", "O", "O"));
        List<String> set178 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "E", "E", "E", "E"));
        List<String> set179 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "O", "O", "O", "E"));
        List<String> set180 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "E", "E", "E", "O"));
        List<String> set181 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "O", "O", "E", "E"));
        List<String> set182 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "E", "E", "O", "O"));
        List<String> set183 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "O", "E", "O", "O"));
        List<String> set184 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "E", "O", "E", "E"));
        List<String> set185 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "O", "E", "E", "E"));
        List<String> set186 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "E", "O", "O", "O"));
        List<String> set187 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "O", "E", "E", "O"));
        List<String> set188 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "E", "O", "O", "E"));
        List<String> set189 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "O", "O", "E", "O"));
        List<String> set190 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "E", "E", "O", "E"));
        List<String> set191 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "O", "E", "O", "E"));
        List<String> set192 = new ArrayList<>(Arrays.asList("E", "O", "O", "O", "E", "O", "E", "O"));
        List<String> set193 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "O", "O", "O", "O"));
        List<String> set194 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "E", "E", "E", "E"));
        List<String> set195 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "O", "O", "O", "E"));
        List<String> set196 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "E", "E", "E", "O"));
        List<String> set197 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "O", "O", "E", "E"));
        List<String> set198 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "E", "E", "O", "O"));
        List<String> set199 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "O", "E", "O", "O"));
        List<String> set200 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "E", "O", "E", "E"));
        List<String> set201 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "O", "E", "E", "E"));
        List<String> set202 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "E", "O", "O", "O"));
        List<String> set203 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "O", "E", "E", "O"));
        List<String> set204 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "E", "O", "O", "E"));
        List<String> set205 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "O", "O", "E", "O"));
        List<String> set206 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "E", "E", "O", "E"));
        List<String> set207 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "O", "E", "O", "E"));
        List<String> set208 = new ArrayList<>(Arrays.asList("E", "O", "O", "E", "E", "O", "E", "O"));
        List<String> set209 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "O", "O", "O", "O"));
        List<String> set210 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "E", "E", "E", "E"));
        List<String> set211 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "O", "O", "O", "E"));
        List<String> set212 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "E", "E", "E", "O"));
        List<String> set213 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "O", "O", "E", "E"));
        List<String> set214 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "E", "E", "O", "O"));
        List<String> set215 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "O", "E", "O", "O"));
        List<String> set216 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "E", "O", "E", "E"));
        List<String> set217 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "O", "E", "E", "E"));
        List<String> set218 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "E", "O", "O", "O"));
        List<String> set219 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "O", "E", "E", "O"));
        List<String> set220 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "E", "O", "O", "E"));
        List<String> set221 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "O", "O", "E", "O"));
        List<String> set222 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "E", "E", "O", "E"));
        List<String> set223 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "O", "E", "O", "E"));
        List<String> set224 = new ArrayList<>(Arrays.asList("O", "E", "E", "O", "E", "O", "E", "O"));
        List<String> set225 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "O", "O", "O", "O"));
        List<String> set226 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "E", "E", "E", "E"));
        List<String> set227 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "O", "O", "O", "E"));
        List<String> set228 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "E", "E", "E", "O"));
        List<String> set229 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "O", "O", "E", "E"));
        List<String> set230 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "E", "E", "O", "O"));
        List<String> set231 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "O", "E", "O", "O"));
        List<String> set232 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "E", "O", "E", "E"));
        List<String> set233 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "O", "E", "E", "E"));
        List<String> set234 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "E", "O", "O", "O"));
        List<String> set235 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "O", "E", "E", "O"));
        List<String> set236 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "E", "O", "O", "E"));
        List<String> set237 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "O", "O", "E", "O"));
        List<String> set238 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "E", "E", "O", "E"));
        List<String> set239 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "O", "E", "O", "E"));
        List<String> set240 = new ArrayList<>(Arrays.asList("O", "O", "E", "E", "E", "O", "E", "O"));
        List<String> set241 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "O", "O", "O", "O"));
        List<String> set242 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "E", "E", "E", "E"));
        List<String> set243 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "O", "O", "O", "E"));
        List<String> set244 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "E", "E", "E", "O"));
        List<String> set245 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "O", "O", "E", "E"));
        List<String> set246 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "E", "E", "O", "O"));
        List<String> set247 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "O", "E", "O", "O"));
        List<String> set248 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "E", "O", "E", "E"));
        List<String> set249 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "O", "E", "E", "E"));
        List<String> set250 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "E", "O", "O", "O"));
        List<String> set251 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "O", "E", "E", "O"));
        List<String> set252 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "E", "O", "O", "E"));
        List<String> set253 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "O", "O", "E", "O"));
        List<String> set254 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "E", "E", "O", "E"));
        List<String> set255 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "O", "E", "O", "E"));
        List<String> set256 = new ArrayList<>(Arrays.asList("E", "E", "O", "O", "E", "O", "E", "O"));


        List<List<String>> setCollection = new ArrayList<>();
        setCollection.add(set1);
        setCollection.add(set2);
        setCollection.add(set3);
        setCollection.add(set4);
        setCollection.add(set5);
        setCollection.add(set6);
        setCollection.add(set7);
        setCollection.add(set8);
        setCollection.add(set9);
        setCollection.add(set10);
        setCollection.add(set11);
        setCollection.add(set12);
        setCollection.add(set13);
        setCollection.add(set14);
        setCollection.add(set15);
        setCollection.add(set16);
        setCollection.add(set17);
        setCollection.add(set18);
        setCollection.add(set19);
        setCollection.add(set20);
        setCollection.add(set21);
        setCollection.add(set22);
        setCollection.add(set23);
        setCollection.add(set24);
        setCollection.add(set25);
        setCollection.add(set26);
        setCollection.add(set27);
        setCollection.add(set28);
        setCollection.add(set29);
        setCollection.add(set30);
        setCollection.add(set31);
        setCollection.add(set32);
        setCollection.add(set33);
        setCollection.add(set34);
        setCollection.add(set35);
        setCollection.add(set36);
        setCollection.add(set37);
        setCollection.add(set38);
        setCollection.add(set39);
        setCollection.add(set40);
        setCollection.add(set41);
        setCollection.add(set42);
        setCollection.add(set43);
        setCollection.add(set44);
        setCollection.add(set45);
        setCollection.add(set46);
        setCollection.add(set47);
        setCollection.add(set48);
        setCollection.add(set49);
        setCollection.add(set50);
        setCollection.add(set51);
        setCollection.add(set52);
        setCollection.add(set53);
        setCollection.add(set54);
        setCollection.add(set55);
        setCollection.add(set56);
        setCollection.add(set57);
        setCollection.add(set58);
        setCollection.add(set59);
        setCollection.add(set60);
        setCollection.add(set61);
        setCollection.add(set62);
        setCollection.add(set63);
        setCollection.add(set64);
        setCollection.add(set65);
        setCollection.add(set66);
        setCollection.add(set67);
        setCollection.add(set68);
        setCollection.add(set69);
        setCollection.add(set70);
        setCollection.add(set71);
        setCollection.add(set72);
        setCollection.add(set73);
        setCollection.add(set74);
        setCollection.add(set75);
        setCollection.add(set76);
        setCollection.add(set77);
        setCollection.add(set78);
        setCollection.add(set79);
        setCollection.add(set80);
        setCollection.add(set81);
        setCollection.add(set82);
        setCollection.add(set83);
        setCollection.add(set84);
        setCollection.add(set85);
        setCollection.add(set86);
        setCollection.add(set87);
        setCollection.add(set88);
        setCollection.add(set89);
        setCollection.add(set90);
        setCollection.add(set91);
        setCollection.add(set92);
        setCollection.add(set93);
        setCollection.add(set94);
        setCollection.add(set95);
        setCollection.add(set96);
        setCollection.add(set97);
        setCollection.add(set98);
        setCollection.add(set99);
        setCollection.add(set100);
        setCollection.add(set101);
        setCollection.add(set102);
        setCollection.add(set103);
        setCollection.add(set104);
        setCollection.add(set105);
        setCollection.add(set106);
        setCollection.add(set107);
        setCollection.add(set108);
        setCollection.add(set109);
        setCollection.add(set110);
        setCollection.add(set111);
        setCollection.add(set112);
        setCollection.add(set113);
        setCollection.add(set114);
        setCollection.add(set115);
        setCollection.add(set116);
        setCollection.add(set117);
        setCollection.add(set118);
        setCollection.add(set119);
        setCollection.add(set120);
        setCollection.add(set121);
        setCollection.add(set122);
        setCollection.add(set123);
        setCollection.add(set124);
        setCollection.add(set125);
        setCollection.add(set126);
        setCollection.add(set127);
        setCollection.add(set128);
        setCollection.add(set129);
        setCollection.add(set130);
        setCollection.add(set131);
        setCollection.add(set132);
        setCollection.add(set133);
        setCollection.add(set134);
        setCollection.add(set135);
        setCollection.add(set136);
        setCollection.add(set137);
        setCollection.add(set138);
        setCollection.add(set139);
        setCollection.add(set140);
        setCollection.add(set141);
        setCollection.add(set142);
        setCollection.add(set143);
        setCollection.add(set144);
        setCollection.add(set145);
        setCollection.add(set146);
        setCollection.add(set147);
        setCollection.add(set148);
        setCollection.add(set149);
        setCollection.add(set150);
        setCollection.add(set151);
        setCollection.add(set152);
        setCollection.add(set153);
        setCollection.add(set154);
        setCollection.add(set155);
        setCollection.add(set156);
        setCollection.add(set157);
        setCollection.add(set158);
        setCollection.add(set159);
        setCollection.add(set160);
        setCollection.add(set161);
        setCollection.add(set162);
        setCollection.add(set163);
        setCollection.add(set164);
        setCollection.add(set165);
        setCollection.add(set166);
        setCollection.add(set167);
        setCollection.add(set168);
        setCollection.add(set169);
        setCollection.add(set170);
        setCollection.add(set171);
        setCollection.add(set172);
        setCollection.add(set173);
        setCollection.add(set174);
        setCollection.add(set175);
        setCollection.add(set176);
        setCollection.add(set177);
        setCollection.add(set178);
        setCollection.add(set179);
        setCollection.add(set180);
        setCollection.add(set181);
        setCollection.add(set182);
        setCollection.add(set183);
        setCollection.add(set184);
        setCollection.add(set185);
        setCollection.add(set186);
        setCollection.add(set187);
        setCollection.add(set188);
        setCollection.add(set189);
        setCollection.add(set190);
        setCollection.add(set191);
        setCollection.add(set192);
        setCollection.add(set193);
        setCollection.add(set194);
        setCollection.add(set195);
        setCollection.add(set196);
        setCollection.add(set197);
        setCollection.add(set198);
        setCollection.add(set199);
        setCollection.add(set200);
        setCollection.add(set201);
        setCollection.add(set202);
        setCollection.add(set203);
        setCollection.add(set204);
        setCollection.add(set205);
        setCollection.add(set206);
        setCollection.add(set207);
        setCollection.add(set208);
        setCollection.add(set209);
        setCollection.add(set210);
        setCollection.add(set211);
        setCollection.add(set212);
        setCollection.add(set213);
        setCollection.add(set214);
        setCollection.add(set215);
        setCollection.add(set216);
        setCollection.add(set217);
        setCollection.add(set218);
        setCollection.add(set219);
        setCollection.add(set220);
        setCollection.add(set221);
        setCollection.add(set222);
        setCollection.add(set223);
        setCollection.add(set224);
        setCollection.add(set225);
        setCollection.add(set226);
        setCollection.add(set227);
        setCollection.add(set228);
        setCollection.add(set229);
        setCollection.add(set230);
        setCollection.add(set231);
        setCollection.add(set232);
        setCollection.add(set233);
        setCollection.add(set234);
        setCollection.add(set235);
        setCollection.add(set236);
        setCollection.add(set237);
        setCollection.add(set238);
        setCollection.add(set239);
        setCollection.add(set240);
        setCollection.add(set241);
        setCollection.add(set242);
        setCollection.add(set243);
        setCollection.add(set244);
        setCollection.add(set245);
        setCollection.add(set246);
        setCollection.add(set247);
        setCollection.add(set248);
        setCollection.add(set249);
        setCollection.add(set250);
        setCollection.add(set251);
        setCollection.add(set252);
        setCollection.add(set253);
        setCollection.add(set254);
        setCollection.add(set255);
        setCollection.add(set256);

        return setCollection;
    }


    public List<List<String>> getC2bet4() {
        List<List<String>> collection = new ArrayList<>();

        List<String> set1 = new ArrayList<>(Arrays.asList("E", "E", "E", "E"));
        List<String> set2 = new ArrayList<>(Arrays.asList("E", "E", "O", "E"));
        List<String> set3 = new ArrayList<>(Arrays.asList("O", "O", "O", "O"));
        List<String> set4 = new ArrayList<>(Arrays.asList("O", "O", "E", "O"));
        collection.add(set1);
        collection.add(set2);
        collection.add(set3);
        collection.add(set4);

        return collection;
    }

    public List<List<String>> getMoneyPicker16() {
        List<List<String>> collection = new ArrayList<>();

        List<String> set1 = new ArrayList<>(Arrays.asList("O", "O", "O", "O"));
        List<String> set2 = new ArrayList<>(Arrays.asList("O", "O", "O", "E"));
        List<String> set3 = new ArrayList<>(Arrays.asList("O", "O", "E", "O"));
        List<String> set4 = new ArrayList<>(Arrays.asList("O", "E", "O", "O"));
        List<String> set5 = new ArrayList<>(Arrays.asList("O", "E", "E", "E"));
        List<String> set6 = new ArrayList<>(Arrays.asList("O", "E", "O", "E"));
        List<String> set7 = new ArrayList<>(Arrays.asList("O", "E", "E", "O"));
        List<String> set8 = new ArrayList<>(Arrays.asList("O", "O", "E", "E"));

        List<String> set9 = new ArrayList<>(Arrays.asList("E", "E", "E", "E"));
        List<String> set10 = new ArrayList<>(Arrays.asList("E", "E", "E", "O"));
        List<String> set11 = new ArrayList<>(Arrays.asList("E", "E", "O", "E"));
        List<String> set12 = new ArrayList<>(Arrays.asList("E", "O", "E", "E"));
        List<String> set13 = new ArrayList<>(Arrays.asList("E", "O", "O", "O"));
        List<String> set14 = new ArrayList<>(Arrays.asList("E", "O", "O", "E"));
        List<String> set15 = new ArrayList<>(Arrays.asList("E", "O", "E", "O"));
        List<String> set16 = new ArrayList<>(Arrays.asList("E", "E", "O", "O"));
        collection.add(set1);
        collection.add(set2);
        collection.add(set3);
        collection.add(set4);
        collection.add(set5);
        collection.add(set6);
        collection.add(set7);
        collection.add(set8);
        collection.add(set9);
        collection.add(set10);
        collection.add(set11);
        collection.add(set12);
        collection.add(set13);
        collection.add(set14);
        collection.add(set15);
        collection.add(set16);
        return collection;
    }


}
